### ISSUE TITLE
changing the name to awesome-macOS

### ISSUE THREAD

**Issue by rahulkapoor90** [iCHAIT/awesome-macOS#307]
As WWDC is approaching and it is somewhat confirmed osx will now be called macOS, would you be changing this repository's name to awesome-macOS or am i too soon to open an issue right now?

**Comment by herrbischoff** [comment]
> it is somewhat confirmed osx will now be called macOS

Nothing has been confirmed, not in the least. It's the press running wild with what little information they have. It's speculation and hearsay.

> or am i too soon to open an issue right now

If you can answer the (useless) question yourself, why ask (the useless question) in public? Your issue is in essence the equivalent of "FIRST!" posts in comment sections. Don't be an overzealous, stupid teenager. Please close this issue. If there is going to be any kind of talk about a name change *at all*, this will take place *after* product name changes are officially confirmed.

**Comment by rahulkapoor90** [comment]
Okay, Captain sassy.

**Comment by herrbischoff** [comment]
Good to see the kids are having their fun.

**Comment by rahulkapoor90** [comment]
stupid teenager was right!

![2016-06-13_23-07-20](https://cloud.githubusercontent.com/assets/11207756/16017070/d5be650e-31bb-11e6-80e8-6cbd3297f664.png)

**Comment by dufferzafar** [comment]
A lot of other people are doing this too! https://github.com/mathiasbynens/dotfiles/commit/47268d92afbec69e3a7243a144a126bbd25bcf2c
