### ISSUE TITLE
Change Awesome label

### ISSUE THREAD

**Issue by iCHAIT** [iCHAIT/awesome-macOS#322]
[Awesome OS X](https://github.com/iCHAIT/awesome-macOS/blob/master/media/awesome.svg) label needs to be changed to **Awesome macOS**.

@herrbischoff Can you help with this since you designed the original label?.

**Comment by herrbischoff** [comment]
@iCHAIT: I'm on it.

**Comment by herrbischoff** [comment]
Here you go. Two text logos, one with the new Display variant for screen use (-display) and one with the UI variant (-ui). The latter should only be used in a GUI context but I included it because the original logo used that typeface.

[logos.zip](https://github.com/iCHAIT/awesome-macOS/files/353883/logos.zip)

Feel free to choose whatever version you like.

**Comment by iCHAIT** [comment]
Hey @herrbischoff  thanks for reverting so quickly, will use one of them.

Thanks :tada:

**Comment by rogersachan** [comment]
Micro description still says Mac OS X, when will this be fixed?

**Comment by iCHAIT** [comment]
Fixed in 88a70b4ee51f209e91ad794640f9746dd4484a80, thanks @herrbischoff :smile:

@rogersachan I think its fixed now :)
