### ISSUE TITLE
Reconsider electron apps?

### ISSUE THREAD

**Issue by lostdesign** [iCHAIT/awesome-macOS#579]
As mentioned in the one PR that removed all electron based apps, why not add apps that are awesome, because of their functionality and quality?

Who cares what technology was used? I mean I could put up an app on the app store and nobody could tell it was an electron app.

I think it's not really a good way of managing an "awesome" list when _awesome_ apps are excluded, just because of the techstack they have been implemented in.

What is the reasoning for this? You get an executable for macos.

**Comment by herrbischoff** [comment]
This was explained back when they were removed. There is no need to have the discussion again.

A cross-platform application that leverages none of the target UI and UX conventions or technologies can never rival a native application. Since this list is called "Awesome macOS", no matter how _useful_ the application may be to _you_, it's not _awesome_ because it does not play to macOS's strengths in a meaningful way. A single web app wrapped inside a full web browser engine wrapped inside a platform binary that eats hundreds of megabytes of disk space and gigabytes of RAM is also decidedly not awesome.

Future questions regarding this will be closed with a reference to this issue.

On a personal note, I entirely don't get why this request pops up from time to time. There are hundreds, née thousands of "Awesome" lists, best-of articles and such like, listing every freaking application under the sun. There is even a "Awesome Electron" list if that's your poison. This list's authors decided to be more selective, to be different. Treat it as a free resource. Add to it when you feel you found something special. But please don't argue about/for points that have been resolved long ago.
